name: Cypress Tests

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cypress run
        uses: cypress-io/github-action@v6

      - name: Upload screenshots to argos-ci.com
        run: npm exec -- argos upload ./cypress/screenshots
        env:
          ARGOS_TOKEN: ${{ secrets.ARGOS_TOKEN }}
